# Generated by Django 5.1 on 2024-09-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_rename_birth_data_application_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='contract_url',
            field=models.CharField(blank=tuple, max_length=255, null=True),
        ),
    ]
